UserType:
  type: string
  description: 用户类型
  enum:
    - NORMAL
    - ADMIN
    - AUDIT
  x-enum:
    - value: NORMAL
      label: NORMAL
    - value: ADMIN
      label: ADMIN
    - value: AUDIT
      label: AUDIT











