openapi: 3.0.0
info:
  version: 1.0.0
  title: aaa
  description: |
    aaa

servers:
  - description: local mock
    name: local_mock
    url: '/api/v1'
x-baseurl: /api/v1

paths:
components:
  schemas:
  requestBodies:
x-generations:
